### ISSUE TITLE
applyment_submit

### ISSUE THREAD

**Issue by realwrtoff** [minibear2021/wechatpayv3#13]
path should end with ‘/’， path = '/v3/applyment4sub/applyment/'， otherwise will return 404.
Also，some field should encrypt too, add logic as follows in **applyment_submit** function:
    if params.get('subject_info').get('identity_info'):
        id_card_info = params.get('subject_info').get('identity_info').get('id_card_info')
        if id_card_info is not None:
            id_card_info['id_card_name'] = self._core.encrypt(id_card_info['id_card_name'])
            id_card_info['id_card_number'] = self._core.encrypt(id_card_info['id_card_number'])
            cipher_data = True

**Comment by minibear2021** [comment]
fixed
