### ISSUE TITLE
微信支付分退款接口无法使用

### ISSUE THREAD

**Issue by MacGuffinLife** [minibear2021/wechatpayv3#16]
该接口在return refund时掉了一个self参数。因此会报如下错误：
 File "/usr/local/lib/python3.9/site-packages/wechatpayv3/payscore.py", line 361, in payscore_refund
sharedpowerbankdocker-web_api-1  |     return refund(out_refund_no=out_refund_no, amount=amount, transaction_id=transaction_id, reason=reason,
sharedpowerbankdocker-web_api-1  | TypeError: refund() missing 1 required positional argument: 'self'

**Comment by MacGuffinLife** [comment]
已提交pr

**Comment by minibear2021** [comment]
确认了
