### ISSUE TITLE
支付成功异步通知里的验签一直失败

### ISSUE THREAD

**Issue by zhichaowen** [minibear2021/wechatpayv3#25]
查看参数, headers跟文档的一样, 也按照文档配置了平台证书,但是在验证签名这步一直失败.

**Comment by zhichaowen** [comment]
这是request body 和 header:
![image](https://user-images.githubusercontent.com/106129629/220266870-32deb691-1b85-4848-a1ec-4e9bd4837ad0.png)

框架是Flask.

**Comment by minibear2021** [comment]
仔细阅读一下readme里关于回调的部分，最直接的办法就是使用examples.py用native支付直击做一下验证，如果examples.py不能执行成功，检查自己的参数。如果examples.py的回调处理成功，检查一下自己项目代码。

**Comment by minibear2021** [comment]
没有新的更新就关闭了。
