### ISSUE TITLE
服务商模式不能直接使用吗？

### ISSUE THREAD

**Issue by xingke2023** [minibear2021/wechatpayv3#31]
服务商模式不能直接使用吗？

**Comment by xingke2023** [comment]
core.py好像不是服务商模式用

**Comment by minibear2021** [comment]
初始化的时候partner_mode=True。

**Comment by xingke2023** [comment]
不行，还要填sub_mchid,sub_appid,sp_appid
不知道是什么意思

**Comment by xingke2023** [comment]
我看了 谢谢作者 我现在在改 那个core.py文件不能直接用

**Comment by xingke2023** [comment]
只需要初始化的时候partner_mode=True吗？
其他程序不需要动吗？

**Comment by xingke2023** [comment]
有没有一个服务商下面商户支付的例子呢？

**Comment by xingke2023** [comment]
WeChatPay.__init__() got an unexpected keyword argument 'sp_mchid'

**Comment by xingke2023** [comment]
可以了 openid 要改成 sub_openid
