### ISSUE TITLE
_verify_signature 里的headers 应该小写吧？

### ISSUE THREAD

**Issue by a1120235890** [minibear2021/wechatpayv3#32]
signature = headers.get('Wechatpay-Signature')
        timestamp = headers.get('Wechatpay-Timestamp')
        nonce = headers.get('Wechatpay-Nonce')
        serial_no = headers.get('Wechatpay-Serial')

**Comment by a1120235890** [comment]
signature = headers.get('wechatpay-signature')
    timestamp = headers.get('wechatpay-timestamp')
    nonce = headers.get('wechatpay-nonce')
    serial_no = headers.get('wechatpay-serial')    不改能用？

**Comment by minibear2021** [comment]
没有新的更新就关闭了。
