### ISSUE TITLE
flask框架下支付回调签名验证失败

### ISSUE THREAD

**Issue by gongzhengtang** [minibear2021/wechatpayv3#35]

**Comment by minibear2021** [comment]
看readme

**Comment by gongzhengtang** [comment]
***@***.***
 
发件人： chen gang
发送时间： 2023-07-27 12:47
收件人： minibear2021/wechatpayv3
抄送： gongzhengtang; Author
主题： Re: [minibear2021/wechatpayv3] flask框架下支付回调签名验证失败 (Issue #35)
看readme

**Comment by gongzhengtang** [comment]
![image](https://github.com/minibear2021/wechatpayv3/assets/35482586/642b3a34-19e9-4c13-ac39-c5128c3c2958)
调用方式完全按照 readme写法，使用的flask框架，但在此处验证签名时失败

**Comment by minibear2021** [comment]
要么代码错了，要么参数错了，确定代码ok的话，重置初始化参数后运行examples.py。
