### ISSUE TITLE
FastAPI框架

### ISSUE THREAD

**Issue by NgWaiKong** [minibear2021/wechatpayv3#41]
您好，

请问项目现在对FastAPI支持情况如何？有更契合FastAPI项目接入的方案吗？

**Comment by minibear2021** [comment]
有用户接入过，你可以参考文档尝试一下，现在还没有对应的demo可用。

**Comment by NgWaiKong** [comment]
谢谢，

另外一个问题是关于 Readme demo code 中的“商户证书序列号”，在其他的框架中我没有发现“商户证书序列号”这个称谓逻辑，请问这个是对应哪个字段？在微信支付商户号中有对应的截图吗？谢谢

**Comment by minibear2021** [comment]
https://wechatpay-api.gitbook.io/wechatpay-api-v3/chang-jian-wen-ti/zheng-shu-xiang-guan#ru-he-cha-kan-zheng-shu-xu-lie-hao
