### ISSUE TITLE
请问能支持微信的付款码支付码吗？

### ISSUE THREAD

**Issue by heiheiheibj** [minibear2021/wechatpayv3#44]
https://[pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1](https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1)
就是这个，谢谢

**Comment by minibear2021** [comment]
支持微信支付api v3版，V2版官方已不再维护，建议直接迁移到V3。
https://pay.weixin.qq.com/docs/merchant/products/jsapi-payment/introduction.html
