### ISSUE TITLE
请问此库有没有扫微信收款码收款的接口

### ISSUE THREAD

**Issue by heiheiheibj** [minibear2021/wechatpayv3#52]
就象超市一样，POS录完单后，用扫码枪扫下用户的微信收款码
其它都解决了，就差这个扫收款码
谢谢

**Comment by minibear2021** [comment]
了解一下 v2 版的付款码支付接口，v3 版中官方未支持。

**Comment by heiheiheibj** [comment]
谢谢

**Comment by minibear2021** [comment]
https://pay.weixin.qq.com/doc/v3/merchant/4012382150
微信支付v3版官方接口已支持付款码支付，sdk已更新。
