### ISSUE TITLE
wechatpayv3也支持微信支付服务商吧？

### ISSUE THREAD

**Issue by Odyssey166** [minibear2021/wechatpayv3#6]
大佬，再问一个可能比较普遍的问题。wechatpayv3文档上说：”适用对象wechatpayv3支持微信支付直连商户“，然后给出了接口适配的方法。通过阅读微信支付官方文档，我发现直连商户和服务商的签名验签、加密解密过程都是一样的。API本质上貌似也没什么区别。例如，以下是服务商电商收付通的API列表:
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter3_3_3.shtml

所以我认为wechatpayv3也支持微信支付服务商，只要开发者自己适配相关接口即可。

请问我的理解是正确的吗？

**Comment by minibear2021** [comment]
理论上应该是的，但是因为我没有关注过服务商接口，不排除有些细微的差别，欢迎测试并反馈一下。

**Comment by Odyssey166** [comment]
多谢您的及时回复！服务商还需要”二级商户进件“，比较啰嗦。。。。。。

**Comment by minibear2021** [comment]
没有更新就关闭了
